name: Actualizar TC Web HD
on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecutará cada 3 horas para ganar a la seguridad
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar el navegador invisible (Playwright)
        run: |
          pip install pytest-playwright
          playwright install chromium
      - name: Ejecutar la intercepción
        run: python robot.py
      - name: Guardar la lista HD
        run: |
          git config --global user.name "Robot Interceptor"
          git config --global user.email "robot@mitv.com"
          git add tc.m3u
          git commit -m "Señal HD web actualizada" || echo "Sin cambios"
          git push
