name: Actualizar TC
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Ejecutar el Robot
        run: python robot.py
      - name: Guardar la nueva lista
        run: |
          git config --global user.name "Mi Robot"
          git config --global user.email "robot@mitv.com"
          git add tc.m3u
          git commit -m "Lista actualizada" || exit 0
          git push
